name: CI de Validation

# Quand est-ce qu'on déclenche le robot ?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # On définit le job "test"
  test:
    runs-on: ubuntu-latest  # Le robot utilise la dernière version d'Ubuntu

    steps:
    # 1. Le robot récupère le code
    - name: Checkout du code
      uses: actions/checkout@v3

    # 2. installe Python
    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. installation des outils de test
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # 4. lancement des tests
    - name: Lancement des Tests Unitaires (IVVQ)
      run: |
        pytest
